Was added CRUD functionality for marital states
CCEO/crud-boilerplate pull request #17
Opened 2020-04-21 20:16 UTC by JulioGa1011

2020-04-21 20:41 UTC, GussRw commented on database/seeds/MaritalStatusTableSeeder.php
> +            'created_at'        => Carbon::now()->format('Y-m-d H:i:s'),
No es necesario el format

2020-04-21 20:41 UTC, GussRw commented on resources/js/components/marital-states/MaritalStatesTable.vue
> +                    sortIcon: {
Estos ya estan agregados por default

2020-04-21 20:41 UTC, GussRw commented on app/Http/Controllers/MaritalStatusController.php
> +                            $maritalStatuss = $maritalStatuss->whereBetween(DB::raw('DATE(' . $filter . ')'), [$dates[0], $dates[1]]);
No es necesario usar DB::raw

2020-04-21 21:16 UTC, cesarureno requested changes

2020-04-21 21:16 UTC, cesarureno commented on app/Http/Controllers/MaritalStatusController.php
> +            $_data = $_data->only($columns);
If columns is empty controller doesnt return data, change it and return all columns
```suggestion
            if(count($columns))
                    $_data = $_data->only($columns);
```

2020-04-21 21:16 UTC, cesarureno commented on app/Http/Controllers/MaritalStatusController.php
> +        return MaritalStatus::create($data);
Save memory, directly using the parameters without assigning it to a variable
```suggestion
        return MaritalStatus::create($request->all());
```

2020-04-21 21:16 UTC, cesarureno commented on app/Http/Controllers/MaritalStatusController.php
> +        $maritalStatus->fill($data);
```suggestion
        $maritalStatus->fill($request->all());
```

2020-04-22 04:07 UTC, GussRw approved these changes

2020-04-22 04:12 UTC, cesarureno approved these changes

2020-04-22 04:12 UTC, merged